In [1]:
import pandas as pd
import numpy as np

In [2]:
house_data=pd.read_csv('Data.csv')
house_data.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [3]:
house_data.shape

(13320, 9)

In [4]:
house_data.dtypes

area_type        object
availability     object
location         object
size             object
society          object
total_sqft       object
bath            float64
balcony         float64
price           float64
dtype: object

In [5]:
house_data.describe()

bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [6]:
house_data1=house_data.drop(['area_type','society','availability','balcony'],axis='columns')
house_data1

location       size total_sqft  bath   price
0      Electronic City Phase II      2 BHK       1056   2.0   39.07
1              Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2                   Uttarahalli      3 BHK       1440   2.0   62.00
3            Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                      Kothanur      2 BHK       1200   2.0   51.00
...                         ...        ...        ...   ...     ...
13315                Whitefield  5 Bedroom       3453   4.0  231.00
13316             Richards Town      4 BHK       3600   5.0  400.00
13317     Raja Rajeshwari Nagar      2 BHK       1141   2.0   60.00
13318           Padmanabhanagar      4 BHK       4689   4.0  488.00
13319              Doddathoguru      1 BHK        550   1.0   17.00

[13320 rows x 5 columns]

In [7]:
house_data1.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [8]:
house_data1.shape

(13320, 5)

In [9]:
house_data1.dropna(inplace=True)
house_data1.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [10]:
house_data1.shape

(13246, 5)

In [11]:
house_data1['bhk']=house_data1['size'].apply(lambda x:int(x.split()[0]))

In [12]:
house_data1.bhk.unique()

array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18])

In [13]:
def v_to_f(x):       
    t=x.split('-')
    if len(t)==2:
        x=(float(t[0])+float(t[1]))/2
    else:
        try:
            x=float(t[0])
        except:
            x=None
    return x

In [14]:
house_data1.total_sqft=house_data1.total_sqft.apply(v_to_f)

In [15]:
house_data1=house_data1[house_data1.total_sqft.notnull()]

In [16]:
house_data2=house_data1.copy()

In [17]:
house_data2['price_per_sqft'] = house_data2['price']*100000/house_data2['total_sqft']
house_data2.head()

location       size  total_sqft  bath   price  bhk  \
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2   
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4   
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3   
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3   
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2   

   price_per_sqft  
0     3699.810606  
1     4615.384615  
2     4305.555556  
3     6245.890861  
4     4250.000000

In [18]:
house_data2.describe()#isnull().sum()

total_sqft          bath         price           bhk  price_per_sqft
count  13200.000000  13200.000000  13200.000000  13200.000000    1.320000e+04
mean    1555.302783      2.691136    112.276178      2.800833    7.920759e+03
std     1237.323445      1.338915    149.175995      1.292843    1.067272e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.267701e+03
50%     1275.000000      2.000000     71.850000      3.000000    5.438331e+03
75%     1672.000000      3.000000    120.000000      3.000000    7.317073e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [19]:
house_data2.location=house_data2.location.apply(lambda x:x.strip())

In [20]:
location_stats=house_data2['location'].value_counts(ascending=False)
location_stats

Whitefield                                      533
Sarjapur  Road                                  392
Electronic City                                 304
Kanakpura Road                                  264
Thanisandra                                     235
                                               ... 
Zuzuvadi                                          1
Subramanya Nagar                                  1
Maheswari Nagar                                   1
Lakshminarayanapura, Electronic City Phase 2      1
1st Stage Domlur                                  1
Name: location, Length: 1287, dtype: int64

In [21]:
location_stats_less_than_10=location_stats[location_stats<=10]
location_stats_less_than_10

1st Block Koramangala                           10
Kalkere                                         10
Nagadevanahalli                                 10
Sadashiva Nagar                                 10
Gunjur Palya                                    10
                                                ..
Zuzuvadi                                         1
Subramanya Nagar                                 1
Maheswari Nagar                                  1
Lakshminarayanapura, Electronic City Phase 2     1
1st Stage Domlur                                 1
Name: location, Length: 1047, dtype: int64

In [22]:
len(location_stats_less_than_10)

1047

In [23]:
house_data3=house_data2.copy()

In [24]:
house_data3.location=house_data3.location.apply(lambda x:'other' if x in location_stats_less_than_10 else x)

In [25]:
len(house_data3['location'].unique())

241

In [26]:
house_data3.head(10)

location       size  total_sqft  bath   price  bhk  \
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2   
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4   
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3   
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3   
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2   
5                Whitefield      2 BHK      1170.0   2.0   38.00    2   
6          Old Airport Road      4 BHK      2732.0   4.0  204.00    4   
7              Rajaji Nagar      4 BHK      3300.0   4.0  600.00    4   
8              Marathahalli      3 BHK      1310.0   3.0   63.25    3   
9                     other  6 Bedroom      1020.0   6.0  370.00    6   

   price_per_sqft  
0     3699.810606  
1     4615.384615  
2     4305.555556  
3     6245.890861  
4     4250.000000  
5     3247.863248  
6     7467.057101  
7    18181.818182  
8     4828.244275  
9    36274.509804

In [27]:
house_data3[(house_data3.total_sqft/house_data3.bhk < 300)]

location       size  total_sqft  bath  price  bhk  \
9                    other  6 Bedroom      1020.0   6.0  370.0    6   
45              HSR Layout  8 Bedroom       600.0   9.0  200.0    8   
58           Murugeshpalya  6 Bedroom      1407.0   4.0  150.0    6   
68     Devarachikkanahalli  8 Bedroom      1350.0   7.0   85.0    8   
70                   other  3 Bedroom       500.0   3.0  100.0    3   
...                    ...        ...         ...   ...    ...  ...   
13277                other  7 Bedroom      1400.0   7.0  218.0    7   
13279                other  6 Bedroom      1200.0   5.0  130.0    6   
13281      Margondanahalli  5 Bedroom      1375.0   5.0  125.0    5   
13303       Vidyaranyapura  5 Bedroom       774.0   5.0   70.0    5   
13311     Ramamurthy Nagar  7 Bedroom      1500.0   9.0  250.0    7   

       price_per_sqft  
9        36274.509804  
45       33333.333333  
58       10660.980810  
68        6296.296296  
70       20000.000000  
...               ...  
13277    15571.428571  
13279    10833.333333  
13281     9090.909091  
13303     9043.927649  
13311    16666.666667  

[744 rows x 7 columns]

In [28]:
house_data4=house_data3[~(house_data3.total_sqft/house_data3.bhk < 300)]
house_data4.shape

(12456, 7)

In [29]:
house_data4.price_per_sqft.describe()

count     12456.000000
mean       6308.502826
std        4168.127339
min         267.829813
25%        4210.526316
50%        5294.117647
75%        6916.666667
max      176470.588235
Name: price_per_sqft, dtype: float64

<H1>Outlier Removal</H1>

In [30]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft>(m-st)) & (subdf.price_per_sqft<=(m+st))]
        df_out = pd.concat([df_out,reduced_df],ignore_index=True)
    return df_out
house_data5 = remove_pps_outliers(house_data4)
house_data5.shape

(10242, 7)

In [31]:
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk-1)
            if stats and stats['count']>5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft<(stats['mean'])].index.values)
    return df.drop(exclude_indices,axis='index')
house_data6 = remove_bhk_outliers(house_data5)
house_data6.shape

(7317, 7)

In [32]:
house_data6[house_data6.bath>10]

location    size  total_sqft  bath  price  bhk  price_per_sqft
5277  Neeladri Nagar  10 BHK      4000.0  12.0  160.0   10     4000.000000
8483           other  10 BHK     12000.0  12.0  525.0   10     4375.000000
8572           other  16 BHK     10000.0  16.0  550.0   16     5500.000000
9306           other  11 BHK      6000.0  12.0  150.0   11     2500.000000
9637           other  13 BHK      5425.0  13.0  275.0   13     5069.124424

In [33]:
house_data7 = house_data6[house_data6.bath<house_data6.bhk+2]
house_data7.shape

(7239, 7)

house_data1['price_per_sqft']=house_data1['price']*100000/house_data1['total_sqft']

In [34]:
house_data8 = house_data7.drop(['size','price_per_sqft'],axis='columns')
house_data8.head(3)

location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3

In [35]:
dum_data=pd.get_dummies(house_data8['location'])
dum_data

1st Block Jayanagar  1st Phase JP Nagar  2nd Phase Judicial Layout  \
0                        1                   0                          0   
1                        1                   0                          0   
2                        1                   0                          0   
3                        1                   0                          0   
4                        1                   0                          0   
...                    ...                 ...                        ...   
10233                    0                   0                          0   
10234                    0                   0                          0   
10237                    0                   0                          0   
10238                    0                   0                          0   
10241                    0                   0                          0   

       2nd Stage Nagarbhavi  5th Block Hbr Layout  5th Phase JP Nagar  \
0                         0                     0                   0   
1                         0                     0                   0   
2                         0                     0                   0   
3                         0                     0                   0   
4                         0                     0                   0   
...                     ...                   ...                 ...   
10233                     0                     0                   0   
10234                     0                     0                   0   
10237                     0                     0                   0   
10238                     0                     0                   0   
10241                     0                     0                   0   

       6th Phase JP Nagar  7th Phase JP Nagar  8th Phase JP Nagar  \
0                       0                   0                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   0   
4                       0                   0                   0   
...                   ...                 ...                 ...   
10233                   0                   0                   0   
10234                   0                   0                   0   
10237                   0                   0                   0   
10238                   0                   0                   0   
10241                   0                   0                   0   

       9th Phase JP Nagar  ...  Vishveshwarya Layout  Vishwapriya Layout  \
0                       0  ...                     0                   0   
1                       0  ...                     0                   0   
2                       0  ...                     0                   0   
3                       0  ...                     0                   0   
4                       0  ...                     0                   0   
...                   ...  ...                   ...                 ...   
10233                   0  ...                     0                   0   
10234                   0  ...                     0                   0   
10237                   0  ...                     0                   0   
10238                   0  ...                     0                   0   
10241                   0  ...                     0                   0   

       Vittasandra  Whitefield  Yelachenahalli  Yelahanka  Yelahanka New Town  \
0                0           0               0          0                   0   
1                0           0               0          0                   0   
2                0           0               0          0                   0   
3                0           0               0          0                   0   
4                0           0               0          0 

In [36]:
house_data9=pd.concat([house_data8, dum_data],axis='columns')

In [37]:
house_data9.head()

location  total_sqft  bath  price  bhk  1st Block Jayanagar  \
0  1st Block Jayanagar      2850.0   4.0  428.0    4                    1   
1  1st Block Jayanagar      1630.0   3.0  194.0    3                    1   
2  1st Block Jayanagar      1875.0   2.0  235.0    3                    1   
3  1st Block Jayanagar      1200.0   2.0  130.0    3                    1   
4  1st Block Jayanagar      1235.0   2.0  148.0    2                    1   

   1st Phase JP Nagar  2nd Phase Judicial Layout  2nd Stage Nagarbhavi  \
0                   0                          0                     0   
1                   0                          0                     0   
2                   0                          0                     0   
3                   0                          0                     0   
4                   0                          0                     0   

   5th Block Hbr Layout  ...  Vishveshwarya Layout  Vishwapriya Layout  \
0                     0  ...                     0                   0   
1                     0  ...                     0                   0   
2                     0  ...                     0                   0   
3                     0  ...                     0                   0   
4                     0  ...                     0                   0   

   Vittasandra  Whitefield  Yelachenahalli  Yelahanka  Yelahanka New Town  \
0            0           0               0          0                   0   
1            0           0               0          0                   0   
2            0           0               0          0                   0   
3            0           0               0          0                   0   
4            0           0               0          0                   0   

   Yelenahalli  Yeshwanthpur  other  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0  

[5 rows x 246 columns]

In [38]:
house_data10=house_data9.drop(['location'],axis='columns')
house_data10.head()

total_sqft  bath  price  bhk  1st Block Jayanagar  1st Phase JP Nagar  \
0      2850.0   4.0  428.0    4                    1                   0   
1      1630.0   3.0  194.0    3                    1                   0   
2      1875.0   2.0  235.0    3                    1                   0   
3      1200.0   2.0  130.0    3                    1                   0   
4      1235.0   2.0  148.0    2                    1                   0   

   2nd Phase Judicial Layout  2nd Stage Nagarbhavi  5th Block Hbr Layout  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     0                     0   
3                          0                     0                     0   
4                          0                     0                     0   

   5th Phase JP Nagar  ...  Vishveshwarya Layout  Vishwapriya Layout  \
0                   0  ...                     0                   0   
1                   0  ...                     0                   0   
2                   0  ...                     0                   0   
3                   0  ...                     0                   0   
4                   0  ...                     0                   0   

   Vittasandra  Whitefield  Yelachenahalli  Yelahanka  Yelahanka New Town  \
0            0           0               0          0                   0   
1            0           0               0          0                   0   
2            0           0               0          0                   0   
3            0           0               0          0                   0   
4            0           0               0          0                   0   

   Yelenahalli  Yeshwanthpur  other  
0            0             0      0  
1            0             0      0  
2            0             0      0  
3            0             0      0  
4            0             0      0  

[5 rows x 245 columns]

In [39]:
np.zeros([1,len(house_data5)],float)

array([[0., 0., 0., ..., 0., 0., 0.]])

house_data3['price_per_sqft'].describe()

In [40]:
x=house_data10.drop(['price'],axis='columns')

In [41]:
x.head()

total_sqft  bath  bhk  1st Block Jayanagar  1st Phase JP Nagar  \
0      2850.0   4.0    4                    1                   0   
1      1630.0   3.0    3                    1                   0   
2      1875.0   2.0    3                    1                   0   
3      1200.0   2.0    3                    1                   0   
4      1235.0   2.0    2                    1                   0   

   2nd Phase Judicial Layout  2nd Stage Nagarbhavi  5th Block Hbr Layout  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     0                     0   
3                          0                     0                     0   
4                          0                     0                     0   

   5th Phase JP Nagar  6th Phase JP Nagar  ...  Vishveshwarya Layout  \
0                   0                   0  ...                     0   
1                   0                   0  ...                     0   
2                   0                   0  ...                     0   
3                   0                   0  ...                     0   
4                   0                   0  ...                     0   

   Vishwapriya Layout  Vittasandra  Whitefield  Yelachenahalli  Yelahanka  \
0                   0            0           0               0          0   
1                   0            0           0               0          0   
2                   0            0           0               0          0   
3                   0            0           0               0          0   
4                   0            0           0               0          0   

   Yelahanka New Town  Yelenahalli  Yeshwanthpur  other  
0                   0            0             0      0  
1                   0            0             0      0  
2                   0            0             0      0  
3                   0            0             0      0  
4                   0            0             0      0  

[5 rows x 244 columns]

In [42]:
y=house_data10[['price']]

In [43]:
y.head()

price
0  428.0
1  194.0
2  235.0
3  130.0
4  148.0

In [44]:
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.tree import DecisionTreeRegressor

In [45]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)

In [46]:
cross_val_score(LinearRegression(),x,y,cv=cv)

array([0.82702546, 0.86015354, 0.85221962, 0.84364854, 0.85483617])

In [47]:
cross_val_score(DecisionTreeRegressor(),x,y,cv=cv)

array([0.86738196, 0.86817833, 0.6018176 , 0.46352761, 0.83066593])

In [48]:
cross_val_score(Lasso(),x,y,cv=cv)

array([0.70625266, 0.74533508, 0.74196984, 0.76700756, 0.73309368])

In [49]:
model=LinearRegression()

In [50]:
model.fit(x,y)

LinearRegression()

In [51]:
import pickle

In [53]:
pickle.dump(model, open("BHP_model", 'wb'))

In [55]:
m=pickle.load(open("BHP_model", 'rb'))

In [56]:
m.score(x,y)

0.854407387005552

In [57]:
import json
columns = {
    'data_columns' : [col.lower() for col in x.columns]
}
with open("columns.json","w") as f:
    f.write(json.dumps(columns))